import type { Profile, Space } from "./types";

// The QR / URL entry point for the first experiment.
export const DEFAULT_VENUE = "blue-tokai-gurgaon";

// Each venue is a distinct facility with its own QR (venueId), its own people,
// and a facility type that drives UI prioritization. Add a row here + a profile
// list below to launch a new facility.
export const SEED_SPACES: Space[] = [
  { id: "space_blue_tokai", venueId: DEFAULT_VENUE, name: "Blue Tokai", facilityType: "cafe" },
  { id: "space_champaca", venueId: "champaca-library", name: "Champaca", facilityType: "library" },
  { id: "space_ironhouse", venueId: "iron-house-gym", name: "Iron House", facilityType: "gym" },
  { id: "space_runclub", venueId: "gurugram-run-club", name: "Gurugram Run Club", facilityType: "run_club" },
  { id: "space_socialhouse", venueId: "social-house-bar", name: "Social House", facilityType: "bar" },
  { id: "space_mixer", venueId: "founders-mixer", name: "Founders Mixer", facilityType: "social" },
];

const now = "2026-08-10T11:00:00.000Z";

type SeedProfile = Omit<Profile, "spaceId" | "createdAt" | "updatedAt">;

// 14 profiles that should read like real regulars, not personas.
const cafePeople: SeedProfile[] = [
  {
    id: "p_aniket",
    name: "Aniket",
    age: 27,
    profession: "Robotics Engineer",
    avatarEmoji: "🧑🏽‍🔧",
    interests: ["Running", "Technology", "Travel", "Philosophy", "Books"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🏃", text: "Training for HYROX" },
      { emoji: "📚", text: "Exploring sociology and technology" },
      { emoji: "✈️", text: "Planning Japan" },
    ],
    interesting: "Started running 6 months ago and still struggle with long runs. Getting there.",
    askMeAbout: ["Japan travel", "HYROX", "Sociology of technology"],
    lookingFor: ["Running partner", "Travel recommendations", "Interesting conversations"],
    recently: "Completed first 50 km running week.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Sunday afternoons",
  },
  {
    id: "p_riya",
    name: "Riya",
    age: 26,
    profession: "Designer",
    avatarEmoji: "👩🏽‍🎨",
    interests: ["Books", "Art", "Travel", "Design", "Coffee"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "📚", text: "Reading Kafka" },
      { emoji: "🎨", text: "Illustrates in her free time" },
      { emoji: "✈️", text: "Travelling to Vietnam next month" },
    ],
    interesting: "I keep a sketchbook of strangers I see in cafés. You might be in it.",
    askMeAbout: ["Books", "Travel", "Art"],
    lookingFor: ["Interesting conversations", "Travel recommendations"],
    recently: "Finished a 30-day daily illustration challenge.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Weekday mornings",
  },
  {
    id: "p_arjun",
    name: "Arjun",
    age: 29,
    profession: "Founder",
    avatarEmoji: "🧑🏻‍💻",
    interests: ["Startups", "Running", "Technology", "Coffee"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🚀", text: "Building an AI startup" },
      { emoji: "🏃", text: "Training for a marathon" },
      { emoji: "☕", text: "Regular Sunday café visitor" },
    ],
    interesting: "On my third startup. The first two taught me more than any degree.",
    askMeAbout: ["Fundraising", "Running", "Early-stage hiring"],
    lookingFor: ["Startup conversations", "Running partner"],
    recently: "Shipped our first paying customer this week.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Sunday mornings",
  },
  {
    id: "p_meera",
    name: "Meera",
    age: 24,
    profession: "PhD Student",
    avatarEmoji: "👩🏽‍🔬",
    interests: ["Philosophy", "Books", "Music", "Writing"],
    currentActivity: "Studying",
    nowLines: [
      { emoji: "🧠", text: "Researching memory and cities" },
      { emoji: "📖", text: "Rereading Borges" },
      { emoji: "🎹", text: "Learning jazz piano" },
    ],
    interesting: "My thesis argues that cities remember us better than we remember them.",
    askMeAbout: ["Philosophy of mind", "Jazz", "Delhi's history"],
    lookingFor: ["Interesting conversations", "New friends"],
    recently: "Presented at my first international conference.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Late afternoons",
  },
  {
    id: "p_kabir",
    name: "Kabir",
    age: 31,
    profession: "Photographer",
    avatarEmoji: "🧑🏾‍🎤",
    interests: ["Photography", "Travel", "Music", "Food"],
    currentActivity: "Exploring",
    nowLines: [
      { emoji: "📷", text: "Shooting a street-food series" },
      { emoji: "🌏", text: "Back from three months in Georgia" },
      { emoji: "🎧", text: "Making a travel playlist" },
    ],
    interesting: "I've photographed 40 countries but the best light is still in old Delhi.",
    askMeAbout: ["Street photography", "Georgia", "Where to eat anywhere"],
    lookingFor: ["People to explore with", "Travel recommendations"],
    recently: "Had a photo picked up by a travel magazine.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Whenever the light is good",
  },
  {
    id: "p_ananya",
    name: "Ananya",
    age: 28,
    profession: "Doctor",
    avatarEmoji: "👩🏻‍⚕️",
    interests: ["Fitness", "Books", "Cooking", "Music"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🏋️", text: "Powerlifting on weekends" },
      { emoji: "🍳", text: "Learning Thai cooking" },
      { emoji: "📚", text: "Reading about longevity" },
    ],
    interesting: "Off a 24-hour shift and pretending caffeine is a personality.",
    askMeAbout: ["Strength training", "Cooking", "Medicine myths"],
    lookingFor: ["Activity partner", "New friends"],
    recently: "Hit a 100 kg deadlift.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Post-shift mornings",
  },
  {
    id: "p_dev",
    name: "Dev",
    age: 33,
    profession: "Musician",
    avatarEmoji: "🧑🏽‍🎤",
    interests: ["Music", "Coffee", "Writing", "Movies"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "🎸", text: "Producing an indie EP" },
      { emoji: "☕", text: "Writes lyrics on café napkins" },
      { emoji: "🎬", text: "Scoring a short film" },
    ],
    interesting: "Every song I've written started as an overheard café conversation.",
    askMeAbout: ["Making music", "Film scores", "Indie gigs in the city"],
    lookingFor: ["Interesting conversations", "People to explore with"],
    recently: "Played my first live set in two years.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekday afternoons",
  },
  {
    id: "p_sara",
    name: "Sara",
    age: 25,
    profession: "Climate Researcher",
    avatarEmoji: "👩🏼‍🔬",
    interests: ["Travel", "Books", "Running", "Food"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "🌱", text: "Working on urban cooling" },
      { emoji: "🏃", text: "Training for a half marathon" },
      { emoji: "📚", text: "Reading Robin Wall Kimmerer" },
    ],
    interesting: "I can tell you which trees in this neighbourhood are quietly saving it.",
    askMeAbout: ["Climate work", "Running routes", "Nature writing"],
    lookingFor: ["Running partner", "Interesting conversations"],
    recently: "Co-authored my first published paper.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Saturday mornings",
  },
  {
    id: "p_ishaan",
    name: "Ishaan",
    age: 30,
    profession: "Chef",
    avatarEmoji: "🧑🏽‍🍳",
    interests: ["Food", "Travel", "Music", "Coffee"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🍜", text: "Opening a ramen pop-up" },
      { emoji: "☕", text: "Obsessed with single-origin coffee" },
      { emoji: "✈️", text: "Just back from Tokyo" },
    ],
    interesting: "I flew to Japan for a week and spent all of it eating ramen. No regrets.",
    askMeAbout: ["Ramen", "Tokyo food", "What to order here"],
    lookingFor: ["People to explore with", "New friends"],
    recently: "Sold out my first supper club.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Between service hours",
  },
  {
    id: "p_tara",
    name: "Tara",
    age: 27,
    profession: "Product Manager",
    avatarEmoji: "👩🏻‍💼",
    interests: ["Startups", "Books", "Fitness", "Philosophy"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "📱", text: "Building a mental-health app" },
      { emoji: "🧘", text: "100 days of yoga" },
      { emoji: "📖", text: "Reading Stoic philosophy" },
    ],
    interesting: "I quit consulting to build something I'd actually use. Terrifying and great.",
    askMeAbout: ["Product", "Yoga", "Stoicism"],
    lookingFor: ["Startup conversations", "Activity partner"],
    recently: "Left my corporate job to go all in.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Weekday mornings",
  },
  {
    id: "p_rohan",
    name: "Rohan",
    age: 35,
    profession: "Architect",
    avatarEmoji: "🧑🏻‍🎨",
    interests: ["Design", "Art", "Photography", "Travel"],
    currentActivity: "Exploring",
    nowLines: [
      { emoji: "🏛️", text: "Designing a public library" },
      { emoji: "📷", text: "Photographs doorways obsessively" },
      { emoji: "🗺️", text: "Sketching a walking tour of the city" },
    ],
    interesting: "I believe cafés are the last great public rooms we have left.",
    askMeAbout: ["Architecture", "City walks", "Good design"],
    lookingFor: ["Interesting conversations", "People to explore with"],
    recently: "Won a competition to redesign a metro station.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Late mornings",
  },
  {
    id: "p_nikita",
    name: "Nikita",
    age: 23,
    profession: "Film Student",
    avatarEmoji: "👩🏽‍🎓",
    interests: ["Movies", "Music", "Writing", "Art"],
    currentActivity: "Studying",
    nowLines: [
      { emoji: "🎬", text: "Editing her first short film" },
      { emoji: "🎞️", text: "On a French New Wave binge" },
      { emoji: "✍️", text: "Writing a screenplay" },
    ],
    interesting: "I'll defend that the café scene in any film tells you everything about it.",
    askMeAbout: ["Cinema", "Screenwriting", "What to watch tonight"],
    lookingFor: ["New friends", "Interesting conversations"],
    recently: "Got into a film festival's student program.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Evenings",
  },
  {
    id: "p_vikram",
    name: "Vikram",
    age: 38,
    profession: "Investor",
    avatarEmoji: "🧑🏾‍💼",
    interests: ["Startups", "Books", "Running", "Coffee"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "📈", text: "Backing early climate startups" },
      { emoji: "🏃", text: "Marathon number seven this year" },
      { emoji: "📚", text: "Reading a biography a week" },
    ],
    interesting: "I've read 200 pitch decks this month and one book that beat all of them.",
    askMeAbout: ["Raising money", "Marathons", "Book recommendations"],
    lookingFor: ["Startup conversations", "Running partner"],
    recently: "Ran the Berlin marathon.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Early mornings",
  },
  {
    id: "p_zoya",
    name: "Zoya",
    age: 29,
    profession: "Journalist",
    avatarEmoji: "🧕🏽",
    interests: ["Writing", "Books", "Travel", "Philosophy"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "📰", text: "Reporting a long-form piece on the city" },
      { emoji: "🎙️", text: "Starting a podcast" },
      { emoji: "📖", text: "Reading Svetlana Alexievich" },
    ],
    interesting: "My job is basically talking to strangers. This app might put me out of work.",
    askMeAbout: ["Storytelling", "The city", "Podcasts"],
    lookingFor: ["Interesting conversations", "New friends"],
    recently: "Had a story go front-page.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Afternoons",
  },
];

// --- Library (Champaca) -----------------------------------------------------
const libraryPeople: SeedProfile[] = [
  {
    id: "lib_isha",
    name: "Isha",
    age: 25,
    profession: "Editor",
    avatarEmoji: "👩🏽‍💻",
    interests: ["Books", "Writing", "Philosophy", "Coffee"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "📖", text: "Reading Ocean Vuong" },
      { emoji: "✍️", text: "Editing a debut novel" },
      { emoji: "🧠", text: "Falling down a translation-theory rabbit hole" },
    ],
    interesting: "I judge people by their bookshelves and I'm rarely wrong.",
    askMeAbout: ["Contemporary fiction", "Editing", "Poetry"],
    lookingFor: ["Interesting conversations", "New friends"],
    recently: "Finished a manuscript I'd been editing for a year.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Weekday afternoons",
  },
  {
    id: "lib_raghav",
    name: "Raghav",
    age: 31,
    profession: "History Professor",
    avatarEmoji: "🧑🏽‍🏫",
    interests: ["Books", "Philosophy", "Travel", "Writing"],
    currentActivity: "Studying",
    nowLines: [
      { emoji: "📚", text: "Researching Mughal-era libraries" },
      { emoji: "🗺️", text: "Mapping old trade routes" },
      { emoji: "📖", text: "Rereading Tolstoy for the fourth time" },
    ],
    interesting: "I know an unreasonable amount about how cities got their names.",
    askMeAbout: ["History", "Old Delhi", "What to read next"],
    lookingFor: ["Interesting conversations"],
    recently: "Published a paper on lost libraries.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Mornings",
  },
  {
    id: "lib_meher",
    name: "Meher",
    age: 23,
    profession: "Grad Student",
    avatarEmoji: "🧕🏻",
    interests: ["Philosophy", "Books", "Writing", "Music"],
    currentActivity: "Studying",
    nowLines: [
      { emoji: "🧠", text: "Writing a thesis on ethics of AI" },
      { emoji: "📖", text: "Reading Hannah Arendt" },
      { emoji: "🎹", text: "Learning to read sheet music" },
    ],
    interesting: "Trying to decide if free will exists before my thesis is due.",
    askMeAbout: ["Philosophy", "AI ethics", "Study playlists"],
    lookingFor: ["New friends", "Interesting conversations"],
    recently: "Survived my thesis proposal defence.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Late afternoons",
  },
  {
    id: "lib_tanvi",
    name: "Tanvi",
    age: 28,
    profession: "Illustrator",
    avatarEmoji: "👩🏽‍🎨",
    interests: ["Art", "Books", "Design", "Film"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "🎨", text: "Illustrating a children's book" },
      { emoji: "📚", text: "Reading graphic novels for research" },
      { emoji: "🎬", text: "On a Studio Ghibli rewatch" },
    ],
    interesting: "I read with a pencil — my books are full of tiny drawings.",
    askMeAbout: ["Illustration", "Graphic novels", "Ghibli"],
    lookingFor: ["People to explore with", "Interesting conversations"],
    recently: "Signed my first picture-book deal.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekends",
  },
  {
    id: "lib_karan",
    name: "Karan",
    age: 34,
    profession: "Screenwriter",
    avatarEmoji: "🧑🏻‍💻",
    interests: ["Film", "Writing", "Books", "Music"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "🎬", text: "Writing a mystery series" },
      { emoji: "📖", text: "Reading crime fiction for structure" },
      { emoji: "☕", text: "Powered entirely by filter coffee" },
    ],
    interesting: "Every good story I've written started in a library like this.",
    askMeAbout: ["Screenwriting", "Crime fiction", "Story structure"],
    lookingFor: ["Interesting conversations", "New friends"],
    recently: "Got a series optioned.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekday mornings",
  },
  {
    id: "lib_sana",
    name: "Sana",
    age: 27,
    profession: "Translator",
    avatarEmoji: "👩🏻‍🏫",
    interests: ["Books", "Travel", "Writing", "Philosophy"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "🌐", text: "Translating a Spanish novel" },
      { emoji: "📖", text: "Reading Bolaño in the original" },
      { emoji: "✈️", text: "Saving up for Buenos Aires" },
    ],
    interesting: "I think a lot about the words that don't translate. Ask me one.",
    askMeAbout: ["Languages", "Latin American lit", "Travel"],
    lookingFor: ["Travel recommendations", "Interesting conversations"],
    recently: "Finished translating my first full novel.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Afternoons",
  },
];

// --- Gym (Iron House) -------------------------------------------------------
const gymPeople: SeedProfile[] = [
  {
    id: "gym_rahul",
    name: "Rahul",
    age: 29,
    profession: "Strength Coach",
    avatarEmoji: "🧑🏽‍🏫",
    interests: ["Fitness", "Running", "Food", "Music"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🏋️", text: "Peaking for a powerlifting meet" },
      { emoji: "🥗", text: "Deep in a cut, dreaming of pizza" },
      { emoji: "🎧", text: "Building the ultimate lifting playlist" },
    ],
    interesting: "I'll happily spot you and fix your deadlift for free.",
    askMeAbout: ["Programming", "Powerlifting", "Nutrition"],
    lookingFor: ["Activity partner", "New friends"],
    recently: "Hit a 220kg deadlift.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Evenings",
  },
  {
    id: "gym_priya",
    name: "Priya",
    age: 26,
    profession: "Physiotherapist",
    avatarEmoji: "👩🏻‍⚕️",
    interests: ["Fitness", "Books", "Travel", "Cooking"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🤸", text: "Chasing my first muscle-up" },
      { emoji: "🧘", text: "Mobility nerd, will judge your squat depth" },
      { emoji: "📚", text: "Reading about pain science" },
    ],
    interesting: "I can tell what you did for a living from how you walk.",
    askMeAbout: ["Injury prevention", "Mobility", "Calisthenics"],
    lookingFor: ["Activity partner", "Interesting conversations"],
    recently: "Got my first strict pull-up.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Early mornings",
  },
  {
    id: "gym_arnav",
    name: "Arnav",
    age: 24,
    profession: "Software Engineer",
    avatarEmoji: "🧑🏻‍💻",
    interests: ["Fitness", "Technology", "Gaming", "Music"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "💪", text: "First real bulk, tracking everything" },
      { emoji: "⌚", text: "Optimising my routine like it's code" },
      { emoji: "🎮", text: "Gym then games, that's the whole personality" },
    ],
    interesting: "I made a spreadsheet for my workouts. It has charts.",
    askMeAbout: ["Beginner lifting", "Fitness tech", "Games"],
    lookingFor: ["Activity partner", "New friends"],
    recently: "Finally benched bodyweight.",
    socialMode: "open",
    visible: true,
    usuallyHere: "After work",
  },
  {
    id: "gym_zoya",
    name: "Zoya",
    age: 30,
    profession: "HYROX Athlete",
    avatarEmoji: "🏃🏽‍♀️",
    interests: ["Fitness", "Running", "Travel", "Food"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🔥", text: "Training for HYROX Dubai" },
      { emoji: "🏃", text: "Running intervals that hurt my feelings" },
      { emoji: "✈️", text: "Racing my way around the world" },
    ],
    interesting: "I do fitness races for fun, which my friends find alarming.",
    askMeAbout: ["HYROX", "Conditioning", "Race travel"],
    lookingFor: ["Activity partner", "People to explore with"],
    recently: "Podiumed at a local HYROX.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Mornings",
  },
  {
    id: "gym_dev",
    name: "Dev",
    age: 33,
    profession: "Entrepreneur",
    avatarEmoji: "🧑🏾‍💼",
    interests: ["Fitness", "Startups", "Books", "Coffee"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🏋️", text: "Lifting to think — best ideas come mid-set" },
      { emoji: "🚀", text: "Bootstrapping a fitness app" },
      { emoji: "📖", text: "Reading about habit formation" },
    ],
    interesting: "My best product decisions have all happened on the treadmill.",
    askMeAbout: ["Startups", "Building habits", "Training + work balance"],
    lookingFor: ["Startup conversations", "Activity partner"],
    recently: "Crossed 100 gym days this year.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Middays",
  },
];

// --- Run club (Gurugram Run Club) -------------------------------------------
const runClubPeople: SeedProfile[] = [
  {
    id: "run_aditya",
    name: "Aditya",
    age: 28,
    profession: "Marketer",
    avatarEmoji: "🏃🏽‍♂️",
    interests: ["Running", "Travel", "Music", "Food"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🏃", text: "Training for a sub-2 half" },
      { emoji: "⏱️", text: "Comfortable pace around 5:30/km" },
      { emoji: "🎧", text: "Always looking for long-run playlists" },
    ],
    interesting: "Started running to clear my head, stayed for the post-run chai.",
    askMeAbout: ["Half marathons", "Pacing", "Local routes"],
    lookingFor: ["Running partner", "New friends"],
    recently: "PB'd my 10k by two minutes.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Saturday mornings",
  },
  {
    id: "run_neha",
    name: "Neha",
    age: 32,
    profession: "Dentist",
    avatarEmoji: "👩🏻‍⚕️",
    interests: ["Running", "Fitness", "Books", "Travel"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🥇", text: "First full marathon in 12 weeks" },
      { emoji: "🌄", text: "Loves sunrise long runs" },
      { emoji: "📚", text: "Reading Born to Run again" },
    ],
    interesting: "I signed up for a marathon on a dare and now I can't stop.",
    askMeAbout: ["Marathon training", "Recovery", "Trail running"],
    lookingFor: ["Running partner", "Activity partner"],
    recently: "Ran my longest run yet — 30k.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekend mornings",
  },
  {
    id: "run_sameer",
    name: "Sameer",
    age: 26,
    profession: "Designer",
    avatarEmoji: "🧑🏽‍🎨",
    interests: ["Running", "Design", "Music", "Photography"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "👟", text: "New to running, chasing my first 5k" },
      { emoji: "📷", text: "Shoots the group every Sunday" },
      { emoji: "🎵", text: "Makes a playlist for each route" },
    ],
    interesting: "I'm the slow one at the back taking everyone's photos. Worth it.",
    askMeAbout: ["Starting to run", "Running photography", "Gear"],
    lookingFor: ["Running partner", "New friends"],
    recently: "Ran my first non-stop 5k.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Sunday mornings",
  },
  {
    id: "run_kavya",
    name: "Kavya",
    age: 30,
    profession: "Product Manager",
    avatarEmoji: "🏃🏻‍♀️",
    interests: ["Running", "Startups", "Travel", "Coffee"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🌍", text: "Runs a race in every city she visits" },
      { emoji: "⏱️", text: "Fast pace — 4:50/km on a good day" },
      { emoji: "☕", text: "Post-run coffee is non-negotiable" },
    ],
    interesting: "I've seen more cities at 6am than most people see at all.",
    askMeAbout: ["Race travel", "Speed work", "Running abroad"],
    lookingFor: ["Running partner", "Travel recommendations"],
    recently: "Ran a half in a new city last month.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Saturdays",
  },
  {
    id: "run_imran",
    name: "Imran",
    age: 35,
    profession: "Doctor",
    avatarEmoji: "🧑🏾‍⚕️",
    interests: ["Running", "Fitness", "Books", "Music"],
    currentActivity: "Training",
    nowLines: [
      { emoji: "🏅", text: "Marathon number five this year" },
      { emoji: "🧭", text: "Leads the long-run group" },
      { emoji: "📖", text: "Reading about endurance science" },
    ],
    interesting: "Happy to pace anyone through their first long run. No one left behind.",
    askMeAbout: ["Endurance", "Pacing others", "Injury-free running"],
    lookingFor: ["Running partner", "Interesting conversations"],
    recently: "Paced a friend to their first marathon finish.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Early mornings",
  },
];

// --- Bar (Social House) -----------------------------------------------------
const barPeople: SeedProfile[] = [
  {
    id: "bar_nikhil",
    name: "Nikhil",
    age: 29,
    profession: "Bartender / Musician",
    avatarEmoji: "🧑🏽‍🎤",
    interests: ["Music", "Food", "Travel", "Film"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🎸", text: "Plays a set here on Fridays" },
      { emoji: "🍸", text: "Will invent a cocktail based on your mood" },
      { emoji: "🎬", text: "On a noir film kick" },
    ],
    interesting: "Tell me your favourite song and I'll make you a drink to match.",
    askMeAbout: ["Live music", "Cocktails", "Films"],
    lookingFor: ["Interesting conversations", "People to explore with"],
    recently: "Wrote a song about this bar.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekend nights",
  },
  {
    id: "bar_alia",
    name: "Alia",
    age: 27,
    profession: "Travel Writer",
    avatarEmoji: "👩🏻‍💻",
    interests: ["Travel", "Food", "Books", "Photography"],
    currentActivity: "Exploring",
    nowLines: [
      { emoji: "✈️", text: "Just back from a month in Vietnam" },
      { emoji: "🍜", text: "On a mission to find the best noodles in town" },
      { emoji: "📷", text: "Photographs every meal, unapologetically" },
    ],
    interesting: "Ask me where to eat anywhere in the world. I probably have a list.",
    askMeAbout: ["Travel", "Where to eat", "Solo trips"],
    lookingFor: ["People to explore with", "Travel recommendations"],
    recently: "Published a piece on street food.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekends",
  },
  {
    id: "bar_rohit",
    name: "Rohit",
    age: 31,
    profession: "Startup Founder",
    avatarEmoji: "🧑🏻‍💻",
    interests: ["Startups", "Music", "Food", "Technology"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🚀", text: "Off the clock, finally" },
      { emoji: "🎧", text: "DJs badly but enthusiastically" },
      { emoji: "🍕", text: "Believes every plan improves over pizza" },
    ],
    interesting: "I came here to not talk about work, so ask me anything else.",
    askMeAbout: ["Music", "Food", "Anything but my startup"],
    lookingFor: ["New friends", "Interesting conversations"],
    recently: "Shipped a big launch this week.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Friday evenings",
  },
  {
    id: "bar_maya",
    name: "Maya",
    age: 25,
    profession: "DJ",
    avatarEmoji: "👩🏽‍🎤",
    interests: ["Music", "Art", "Travel", "Photography"],
    currentActivity: "Exploring",
    nowLines: [
      { emoji: "🎶", text: "Digging for old disco records" },
      { emoji: "🌃", text: "Knows every good spot in the city after dark" },
      { emoji: "🎨", text: "Paints her own gig posters" },
    ],
    interesting: "I can tell you where the good music is happening tonight.",
    askMeAbout: ["Music", "Nightlife", "Record shops"],
    lookingFor: ["People to explore with", "New friends"],
    recently: "Played my first big club night.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Late nights",
  },
  {
    id: "bar_farhan",
    name: "Farhan",
    age: 33,
    profession: "Chef",
    avatarEmoji: "🧑🏽‍🍳",
    interests: ["Food", "Travel", "Music", "Coffee"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🍜", text: "Runs a supper club on weekends" },
      { emoji: "🌶️", text: "Will argue about the best biryani, respectfully" },
      { emoji: "✈️", text: "Eats his way through every city he visits" },
    ],
    interesting: "Off tonight, so I'm the one eating instead of cooking for once.",
    askMeAbout: ["Food", "Supper clubs", "Where to eat"],
    lookingFor: ["Interesting conversations", "People to explore with"],
    recently: "Sold out my last supper club in an hour.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Off nights",
  },
];

// --- Social event (Founders Mixer) ------------------------------------------
const socialPeople: SeedProfile[] = [
  {
    id: "soc_ananya",
    name: "Ananya",
    age: 28,
    profession: "Founder — Climate Tech",
    avatarEmoji: "👩🏻‍💼",
    interests: ["Startups", "Technology", "Books", "Running"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🌱", text: "Building carbon-tracking for supply chains" },
      { emoji: "💸", text: "Raising a seed round" },
      { emoji: "🏃", text: "Runs to think" },
    ],
    interesting: "Left a cushy job to make boring supply chains a little greener.",
    askMeAbout: ["Climate tech", "Fundraising", "Hiring"],
    lookingFor: ["Startup conversations", "New friends"],
    recently: "Closed our first enterprise pilot.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Mixers & demo nights",
  },
  {
    id: "soc_vikram",
    name: "Vikram",
    age: 35,
    profession: "Angel Investor",
    avatarEmoji: "🧑🏾‍💼",
    interests: ["Startups", "Books", "Travel", "Philosophy"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "📈", text: "Backing early-stage founders" },
      { emoji: "📚", text: "Reads a biography a week" },
      { emoji: "🌏", text: "Splits time between three cities" },
    ],
    interesting: "I've backed 40 companies and learned the most from the ones that failed.",
    askMeAbout: ["Raising money", "Early-stage", "Book recommendations"],
    lookingFor: ["Startup conversations", "Interesting conversations"],
    recently: "Made my first climate investment.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Founder events",
  },
  {
    id: "soc_riya",
    name: "Riya",
    age: 26,
    profession: "Product Designer",
    avatarEmoji: "👩🏽‍🎨",
    interests: ["Design", "Startups", "Art", "Technology"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🎨", text: "Designing a health app from scratch" },
      { emoji: "🧩", text: "Obsessed with onboarding flows" },
      { emoji: "🚀", text: "Looking to join an early team" },
    ],
    interesting: "I can redesign almost anything on a napkin. Try me.",
    askMeAbout: ["Product design", "Zero-to-one", "Design systems"],
    lookingFor: ["Startup conversations", "New friends"],
    recently: "Shipped a redesign that doubled signups.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Design & startup meetups",
  },
  {
    id: "soc_aakash",
    name: "Aakash",
    age: 30,
    profession: "ML Engineer",
    avatarEmoji: "🧑🏻‍💻",
    interests: ["Technology", "Startups", "Gaming", "Music"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🤖", text: "Building AI agents for small businesses" },
      { emoji: "🧠", text: "Reading every paper he can find" },
      { emoji: "🎮", text: "Unwinds with strategy games" },
    ],
    interesting: "I'll happily explain transformers to you over a drink. Sorry in advance.",
    askMeAbout: ["AI", "Machine learning", "Technical co-founding"],
    lookingFor: ["Startup conversations", "Activity partner"],
    recently: "Open-sourced a tool that hit the front page.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Tech mixers",
  },
  {
    id: "soc_leela",
    name: "Leela",
    age: 27,
    profession: "Writer & Community Lead",
    avatarEmoji: "🧕🏽",
    interests: ["Writing", "Startups", "Books", "Art"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "✍️", text: "Runs a newsletter for founders" },
      { emoji: "🤝", text: "Knows everyone worth knowing here" },
      { emoji: "📖", text: "Reading about community building" },
    ],
    interesting: "If you tell me what you're looking for, I probably know who you should meet.",
    askMeAbout: ["Community", "Writing", "Who to talk to"],
    lookingFor: ["New friends", "Interesting conversations"],
    recently: "Grew the newsletter past 10k readers.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Every mixer",
  },
];

// venueId → the people who seed that facility.
const PROFILES_BY_VENUE: Record<string, SeedProfile[]> = {
  [DEFAULT_VENUE]: cafePeople,
  "champaca-library": libraryPeople,
  "iron-house-gym": gymPeople,
  "gurugram-run-club": runClubPeople,
  "social-house-bar": barPeople,
  "founders-mixer": socialPeople,
};

export function seedProfilesForSpace(space: Space): Profile[] {
  const people = PROFILES_BY_VENUE[space.venueId] ?? [];
  return people.map((p) => ({
    ...p,
    spaceId: space.id,
    createdAt: now,
    updatedAt: now,
  }));
}
