import type { Profile, Space } from "./types";

// The QR / URL entry point for the first experiment.
export const DEFAULT_VENUE = "blue-tokai-gurgaon";

export const SEED_SPACES: Space[] = [
  {
    id: "space_blue_tokai",
    venueId: DEFAULT_VENUE,
    name: "Blue Tokai",
  },
];

const now = "2026-08-10T11:00:00.000Z";

type SeedProfile = Omit<Profile, "spaceId" | "createdAt" | "updatedAt">;

// 14 profiles that should read like real regulars, not personas.
const seedPeople: SeedProfile[] = [
  {
    id: "p_aniket",
    name: "Aniket",
    age: 27,
    profession: "Robotics Engineer",
    avatarEmoji: "🧑🏽‍🔧",
    interests: ["Running", "Technology", "Travel", "Philosophy", "Books"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🏃", text: "Training for HYROX" },
      { emoji: "📚", text: "Exploring sociology and technology" },
      { emoji: "✈️", text: "Planning Japan" },
    ],
    interesting: "Started running 6 months ago and still struggle with long runs. Getting there.",
    askMeAbout: ["Japan travel", "HYROX", "Sociology of technology"],
    lookingFor: ["Running partner", "Travel recommendations", "Interesting conversations"],
    recently: "Completed first 50 km running week.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Sunday afternoons",
  },
  {
    id: "p_riya",
    name: "Riya",
    age: 26,
    profession: "Designer",
    avatarEmoji: "👩🏽‍🎨",
    interests: ["Books", "Art", "Travel", "Design", "Coffee"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "📚", text: "Reading Kafka" },
      { emoji: "🎨", text: "Illustrates in her free time" },
      { emoji: "✈️", text: "Travelling to Vietnam next month" },
    ],
    interesting: "I keep a sketchbook of strangers I see in cafés. You might be in it.",
    askMeAbout: ["Books", "Travel", "Art"],
    lookingFor: ["Interesting conversations", "Travel recommendations"],
    recently: "Finished a 30-day daily illustration challenge.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Weekday mornings",
  },
  {
    id: "p_arjun",
    name: "Arjun",
    age: 29,
    profession: "Founder",
    avatarEmoji: "🧑🏻‍💻",
    interests: ["Startups", "Running", "Technology", "Coffee"],
    currentActivity: "Building something",
    nowLines: [
      { emoji: "🚀", text: "Building an AI startup" },
      { emoji: "🏃", text: "Training for a marathon" },
      { emoji: "☕", text: "Regular Sunday café visitor" },
    ],
    interesting: "On my third startup. The first two taught me more than any degree.",
    askMeAbout: ["Fundraising", "Running", "Early-stage hiring"],
    lookingFor: ["Startup conversations", "Running partner"],
    recently: "Shipped our first paying customer this week.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Sunday mornings",
  },
  {
    id: "p_meera",
    name: "Meera",
    age: 24,
    profession: "PhD Student",
    avatarEmoji: "👩🏽‍🔬",
    interests: ["Philosophy", "Books", "Music", "Writing"],
    currentActivity: "Studying",
    nowLines: [
      { emoji: "🧠", text: "Researching memory and cities" },
      { emoji: "📖", text: "Rereading Borges" },
      { emoji: "🎹", text: "Learning jazz piano" },
    ],
    interesting: "My thesis argues that cities remember us better than we remember them.",
    askMeAbout: ["Philosophy of mind", "Jazz", "Delhi's history"],
    lookingFor: ["Interesting conversations", "New friends"],
    recently: "Presented at my first international conference.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Late afternoons",
  },
  {
    id: "p_kabir",
    name: "Kabir",
    age: 31,
    profession: "Photographer",
    avatarEmoji: "🧑🏾‍🎤",
    interests: ["Photography", "Travel", "Music", "Food"],
    currentActivity: "Exploring",
    nowLines: [
      { emoji: "📷", text: "Shooting a street-food series" },
      { emoji: "🌏", text: "Back from three months in Georgia" },
      { emoji: "🎧", text: "Making a travel playlist" },
    ],
    interesting: "I've photographed 40 countries but the best light is still in old Delhi.",
    askMeAbout: ["Street photography", "Georgia", "Where to eat anywhere"],
    lookingFor: ["People to explore with", "Travel recommendations"],
    recently: "Had a photo picked up by a travel magazine.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Whenever the light is good",
  },
  {
    id: "p_ananya",
    name: "Ananya",
    age: 28,
    profession: "Doctor",
    avatarEmoji: "👩🏻‍⚕️",
    interests: ["Fitness", "Books", "Cooking", "Music"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🏋️", text: "Powerlifting on weekends" },
      { emoji: "🍳", text: "Learning Thai cooking" },
      { emoji: "📚", text: "Reading about longevity" },
    ],
    interesting: "Off a 24-hour shift and pretending caffeine is a personality.",
    askMeAbout: ["Strength training", "Cooking", "Medicine myths"],
    lookingFor: ["Activity partner", "New friends"],
    recently: "Hit a 100 kg deadlift.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Post-shift mornings",
  },
  {
    id: "p_dev",
    name: "Dev",
    age: 33,
    profession: "Musician",
    avatarEmoji: "🧑🏽‍🎤",
    interests: ["Music", "Coffee", "Writing", "Movies"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "🎸", text: "Producing an indie EP" },
      { emoji: "☕", text: "Writes lyrics on café napkins" },
      { emoji: "🎬", text: "Scoring a short film" },
    ],
    interesting: "Every song I've written started as an overheard café conversation.",
    askMeAbout: ["Making music", "Film scores", "Indie gigs in the city"],
    lookingFor: ["Interesting conversations", "People to explore with"],
    recently: "Played my first live set in two years.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Weekday afternoons",
  },
  {
    id: "p_sara",
    name: "Sara",
    age: 25,
    profession: "Climate Researcher",
    avatarEmoji: "👩🏼‍🔬",
    interests: ["Travel", "Books", "Running", "Food"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "🌱", text: "Working on urban cooling" },
      { emoji: "🏃", text: "Training for a half marathon" },
      { emoji: "📚", text: "Reading Robin Wall Kimmerer" },
    ],
    interesting: "I can tell you which trees in this neighbourhood are quietly saving it.",
    askMeAbout: ["Climate work", "Running routes", "Nature writing"],
    lookingFor: ["Running partner", "Interesting conversations"],
    recently: "Co-authored my first published paper.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Saturday mornings",
  },
  {
    id: "p_ishaan",
    name: "Ishaan",
    age: 30,
    profession: "Chef",
    avatarEmoji: "🧑🏽‍🍳",
    interests: ["Food", "Travel", "Music", "Coffee"],
    currentActivity: "Taking a break",
    nowLines: [
      { emoji: "🍜", text: "Opening a ramen pop-up" },
      { emoji: "☕", text: "Obsessed with single-origin coffee" },
      { emoji: "✈️", text: "Just back from Tokyo" },
    ],
    interesting: "I flew to Japan for a week and spent all of it eating ramen. No regrets.",
    askMeAbout: ["Ramen", "Tokyo food", "What to order here"],
    lookingFor: ["People to explore with", "New friends"],
    recently: "Sold out my first supper club.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Between service hours",
  },
  {
    id: "p_tara",
    name: "Tara",
    age: 27,
    profession: "Product Manager",
    avatarEmoji: "👩🏻‍💼",
    interests: ["Startups", "Books", "Fitness", "Philosophy"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "📱", text: "Building a mental-health app" },
      { emoji: "🧘", text: "100 days of yoga" },
      { emoji: "📖", text: "Reading Stoic philosophy" },
    ],
    interesting: "I quit consulting to build something I'd actually use. Terrifying and great.",
    askMeAbout: ["Product", "Yoga", "Stoicism"],
    lookingFor: ["Startup conversations", "Activity partner"],
    recently: "Left my corporate job to go all in.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Weekday mornings",
  },
  {
    id: "p_rohan",
    name: "Rohan",
    age: 35,
    profession: "Architect",
    avatarEmoji: "🧑🏻‍🎨",
    interests: ["Design", "Art", "Photography", "Travel"],
    currentActivity: "Exploring",
    nowLines: [
      { emoji: "🏛️", text: "Designing a public library" },
      { emoji: "📷", text: "Photographs doorways obsessively" },
      { emoji: "🗺️", text: "Sketching a walking tour of the city" },
    ],
    interesting: "I believe cafés are the last great public rooms we have left.",
    askMeAbout: ["Architecture", "City walks", "Good design"],
    lookingFor: ["Interesting conversations", "People to explore with"],
    recently: "Won a competition to redesign a metro station.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Late mornings",
  },
  {
    id: "p_nikita",
    name: "Nikita",
    age: 23,
    profession: "Film Student",
    avatarEmoji: "👩🏽‍🎓",
    interests: ["Movies", "Music", "Writing", "Art"],
    currentActivity: "Studying",
    nowLines: [
      { emoji: "🎬", text: "Editing her first short film" },
      { emoji: "🎞️", text: "On a French New Wave binge" },
      { emoji: "✍️", text: "Writing a screenplay" },
    ],
    interesting: "I'll defend that the café scene in any film tells you everything about it.",
    askMeAbout: ["Cinema", "Screenwriting", "What to watch tonight"],
    lookingFor: ["New friends", "Interesting conversations"],
    recently: "Got into a film festival's student program.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Evenings",
  },
  {
    id: "p_vikram",
    name: "Vikram",
    age: 38,
    profession: "Investor",
    avatarEmoji: "🧑🏾‍💼",
    interests: ["Startups", "Books", "Running", "Coffee"],
    currentActivity: "Reading",
    nowLines: [
      { emoji: "📈", text: "Backing early climate startups" },
      { emoji: "🏃", text: "Marathon number seven this year" },
      { emoji: "📚", text: "Reading a biography a week" },
    ],
    interesting: "I've read 200 pitch decks this month and one book that beat all of them.",
    askMeAbout: ["Raising money", "Marathons", "Book recommendations"],
    lookingFor: ["Startup conversations", "Running partner"],
    recently: "Ran the Berlin marathon.",
    socialMode: "if_approached",
    visible: true,
    usuallyHere: "Early mornings",
  },
  {
    id: "p_zoya",
    name: "Zoya",
    age: 29,
    profession: "Journalist",
    avatarEmoji: "🧕🏽",
    interests: ["Writing", "Books", "Travel", "Philosophy"],
    currentActivity: "Working",
    nowLines: [
      { emoji: "📰", text: "Reporting a long-form piece on the city" },
      { emoji: "🎙️", text: "Starting a podcast" },
      { emoji: "📖", text: "Reading Svetlana Alexievich" },
    ],
    interesting: "My job is basically talking to strangers. This app might put me out of work.",
    askMeAbout: ["Storytelling", "The city", "Podcasts"],
    lookingFor: ["Interesting conversations", "New friends"],
    recently: "Had a story go front-page.",
    socialMode: "open",
    visible: true,
    usuallyHere: "Afternoons",
  },
];

export function seedProfiles(spaceId: string): Profile[] {
  return seedPeople.map((p) => ({
    ...p,
    spaceId,
    createdAt: now,
    updatedAt: now,
  }));
}
